title: gm
baseURL: https://gmarciani.github.io/
languageCode: en-us
paginate: 5
ignoreErrors: ["error-remote-getjson", "error-missing-instagram-accesstoken"]
markup:
  highlight:
    style: manni # nord,manni
    tabWidth: 4
  tableOfContents:
    startLevel: 2
    ordered: true
    endLevel: 3
sitemap:
  changeFreq: daily
  filename: sitemap.xml
enableRobotsTXT: true
services:
  rss:
    limit: -1

params:
  author: Giacomo Marciani
  description: Software Engineer @ Amazon Web Services
  descriptionShort: Software Engineer @ AWS
  copyrightYear: 2021
  keywords: [software, engineering, giacomo, marciani]
  google_analytics: G-FHL6LX6X9S
  social:
    facebook: giacomo.marciani
    twitter: giacomomarciani
    linkedin: giacomomarciani
    youtube: UCOvMuigL8zTw2yMFoMUOfnQ
    instagram: gmarciani
    github: gmarciani
  resume: https://drive.google.com/file/d/1OaY-SgRdnpoFySxSs_KIZ33kRZnSIfbR/view?usp=sharing
  licenses:
    siteDesign:
      licenseName: MIT
      licenseUrl: https://spdx.org/licenses/MIT.html
    siteContent:
      licenseName: CC-BY-NC-SA
      licenseUrl: https://spdx.org/licenses/CC-BY-NC-SA-4.0.html
