title: gmarciani
baseURL: https://gmarciani.github.io/
languageCode: en-us
paginate: 5
ignoreErrors: ["error-remote-getjson", "error-missing-instagram-accesstoken"]

params:
  author: Giacomo Marciani
  description: Software Engineer @ Amazon Web Services
  descriptionShort: Software Engineer @ AWS
  copyrightYear: 2021
  keywords: [software, engineering, giacomo, marciani]
  google_analytics: UA-59215360-6
  social:
    facebook: giacomo.marciani
    twitter: giacomomarciani
    linkedin: giacomomarciani
    youtube: UCOvMuigL8zTw2yMFoMUOfnQ
    #instagram: gmarciani
    github: gmarciani
