title: gmarciani
baseURL: https://gmarciani.s3.eu-west-1.amazonaws.com/
languageCode: en-us
paginate: 5
ignoreErrors: ["error-remote-getjson"]

params:
  author: Giacomo Marciani
  description: Software Engineer @ Amazon Web Services
  copyrightYear: 2020
  keywords: [software, engineering, giacomo, marciani]
  google_analytics: UA-59215360-6
  social:
    facebook: giacomo.marciani
    twitter: giacomomarciani
    linkedin: giacomomarciani
    youtube: UCOvMuigL8zTw2yMFoMUOfnQ
    instagram: gmarciani
    github: gmarciani